declare module '@websanova/vue-auth'
declare module '@websanova/vue-auth/drivers/auth/bearer.js'
declare module '@websanova/vue-auth/drivers/http/axios.1.x.js'
declare module '@websanova/vue-auth/drivers/router/vue-router.2.x.js'
declare module 'vue2-editor/dist/vue2-editor.core.js'